name: Build
on: [push, pull_request]
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    strategy:
      matrix:
        java: [16-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
